### ISSUE TITLE
kafka老是重连，换过kafka的版本也不行

### ISSUE THREAD

**Issue by lijiansgit** [Terry-Mao/goim#170]
zookeeper日志 老是提示goim重新连接：
[2017-02-20 06:09:14,043] WARN caught end of stream exception (org.apache.zookeeper.server.NIOServerCnxn)
EndOfStreamException: Unable to read additional data from client sessionid 0x15a409ab2cd0001, likely client has closed socket
    at org.apache.zookeeper.server.NIOServerCnxn.doIO(NIOServerCnxn.java:228)
    at org.apache.zookeeper.server.NIOServerCnxnFactory.run(NIOServerCnxnFactory.java:208)
    at java.lang.Thread.run(Thread.java:745)
[2017-02-20 06:09:14,044] INFO Closed socket connection for client /10.10.66.15:36325 which had sessionid 0x15a409ab2cd0001 (org.apache.zookeeper.server.NIOServerCnxn)
[2017-02-20 06:09:15,044] INFO Accepted socket connection from /10.10.66.15:37137 (org.apache.zookeeper.server.NIOServerCnxnFactory)
[2017-02-20 06:09:15,044] WARN Connection request from old client /10.10.66.15:37137; will be dropped if server is in r-o mode (org.apache.zookeeper.server.ZooKeeperServer)
[2017-02-20 06:09:15,044] INFO Client attempting to renew session 0x15a409ab2cd0001 at /10.10.66.15:37137 (org.apache.zookeeper.server.ZooKeeperServer)
[2017-02-20 06:09:15,045] INFO Established session 0x15a409ab2cd0001 with negotiated timeout 6000 for client /10.10.66.15:37137 (org.apache.zookeeper.server.ZooKeeperServer)

**Comment by wangxingge** [comment]
估计zookeeper和kafka的问题，作者应该不会管的吧，这也不是GOIM的问题嘛。

**Comment by lijiansgit** [comment]
@wangxingge 关键是日志提示是客户端的问题
